apiVersion: v1
kind: Secret
metadata:
  name: hackathon-starter-secret
  namespace: hackathon-starter
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc3RhbmRhbG9uZS0wLm1vbmdvZGItc3ZjOjI3MDE3L3Rlc3Q/YXV0aFNvdXJjZT1hZG1pbg==

---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-starter-svc
  namespace: hackathon-starter
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hackathon-starter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hackathon-starter
  name: hackathon-starter
  namespace: hackathon-starter
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hackathon-starter
  template:
    metadata:
      labels:
        app: hackathon-starter
    spec:
      containers:
        - name: hackathon-starter
          image: docker.io/storex/hackathon-starter_web
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: hackathon-starter-secret
                  key: MONGODB_URI
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "10m"
              memory: "128Mi"
      priorityClassName: medium-priority